// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHDx9LEHarH9dS1n-Sm8o_iJHAdvLLys',
    appId: '1:1085858819340:web:YOUR_WEB_APP_ID',
    messagingSenderId: '1085858819340',
    projectId: 'safe-5723a',
    authDomain: 'safe-5723a.firebaseapp.com',
    storageBucket: 'safe-5723a.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfHDx9LEHarH9dS1n-Sm8o_iJHAdvLLys',
    appId: '1:1085858819340:android:a6017296dbdb9efc066d29',
    messagingSenderId: '1085858819340',
    projectId: 'safe-5723a',
    storageBucket: 'safe-5723a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfHDx9LEHarH9dS1n-Sm8o_iJHAdvLLys',
    appId: '1:1085858819340:ios:a6017296dbdb9efc066d29',
    messagingSenderId: '1085858819340',
    projectId: 'safe-5723a',
    storageBucket: 'safe-5723a.firebasestorage.app',
    iosBundleId: 'com.safe.safe',
  );
}
